import { UserProvider } from "@auth0/nextjs-auth0/client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import UserBox from "./UserBox";
import fetchCurrentUser from "@/data-access/user";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await fetchCurrentUser();
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <section>
            <UserBox user={user!}></UserBox>
          </section>
          <section>{children}</section>
        </body>
      </UserProvider>
    </html>
  );
}
